function [Synx,Freq,ROCOF,iterations] = PmuFitSave(...
    SignalParams, ...
	DelayCorr, ...
	MagCorr, ...
	F0, ...
	AnalysisCycles, ...
	SampleRate, ...
	Samples ...
)
% Set up the save file
cd('C:\Users\PowerLabNI3\Documents\PMUCAL\Output')
name = 'Saved4PFit.mat';
if exist(name,'file')
    A = open(name);
    P = A.P;
    clear A;
else
    P = struct('SignalParams', {}, 'DelayCorr', {}, 'MagCorr', {}, 'F0', {}, 'AnalysisCycles', {}, 'SampleRate', {}, 'Samples', {});
end

n = length(P)+1;
P(n).SignalParams = SignalParams;
P(n).DelayCorr = DelayCorr;
P(n).MagCorr = MagCorr;
P(n).F0 = F0;
P(n).AnalysisCycles = AnalysisCycles;
P(n).SampleRate = SampleRate;
P(n).Samples = Samples;

save(name,'P')


[Synx,Freq,ROCOF,iterations] = RampFit ( ...
	SignalParams, ...
	DelayCorr, ...
	MagCorr, ...
	F0, ...
	AnalysisCycles, ...
	SampleRate, ...
	Samples ...
);

end

