function [Synx,Freq,ROCOF,iterations] = RampFit ( ...
	SignalParams, ...
	DelayCorr, ...
	MagCorr, ...
	F0, ...
	AnalysisCycles, ...
	SampleRate, ...
	Samples ...
)
Ain = [70,70,70,5,5,5];
Theta = [0, -(2/3)*pi, (2/3)*pi, 0, -(2/3)*pi, (2/3)*pi,];
Synx = (Ain.*exp(-1i.*Theta)).';
Freq = 50;
ROCOF = 0;
iterations=0;
end
