clear all;
% load ('bar.mat');
% 
% RemainingSamples = Y;
% RemainingTime = t0;
% WindowTime = 0;

spd = 24*60*60;     % seconds per day because matlab times are in fractional days since epoch
WindowTime = round((now)*spd);
AnalysisTime = WindowTime+0.02;
dt = .001;
AnalysisCycles = 4;
F0 = 50;
t = (0:dt:AnalysisCycles/(F0)-dt);
WindowIn = [cos(2*pi*F0*t)]';
Y = WindowIn;
t0 = WindowTime+((AnalysisCycles/2)/F0);

msg = sprintf('WindowTime = %s',datestr(datenum(WindowTime/spd),'HH:MM:SS.FFF'));
disp(msg)
msg = sprintf('AnalysisTime = %s',datestr(datenum(AnalysisTime/spd),'HH:MM:SS.FFF'));
disp(msg)
msg = sprintf('t0 = %s',datestr(datenum(t0/spd),'HH:MM:SS.FFF'));
disp(msg)

    
[WindowOut, ...
    WindowTime, ...
    RemainingSamples, ...
    RemainingTime, ...
    Valid, ...
    Continue] = ...
    WindowBuild (...
    WindowIn, ...
    WindowTime, ...
    F0, ...
    AnalysisCycles, ...
    AnalysisTime, ...
    Y, ...
    dt, ...
    t0);
