clear all;
load ('bar.mat');

RemainingSamples = Y;
RemainingTime = t0;


while ~isempty(RemainingSamples)
    AnalysisTime = AnalysisTime + 1/50;
    Y = RemainingSamples;
    t0 = RemainingTime;
    
    [Window, ...
        WindowTime, ...
        RemainingSamples, ...
        RemainingTime, ...
        Valid, ...
        Continue] = ...
        WindowBuild (...
        Window, ...
        WindowTime, ...
        F0, ...
        AnalysisCycles, ...
        AnalysisTime, ...
        Y, ...
        dt, ...
        t0, ...
        numPhases );
    plot(Window)
end