function [Signal] = UserEvtSigWrapper( ...
                               EvtType,...
                               t,...
                               FSamp,...
                               signalparams...
                               )                                      
% To add a user event plugin, add a case with the appropriate
% event type, then call your user-defined Mathscript function
% within the case.
switch EvtType
    case '60255Harm'
        [Signal] = Harm60255Sig(...
                                t,...
                                FSamp,...
                                signalparams);                                                

    otherwise
        msgStr = sprintf('EventType %s not found in UserEvtRptWrapper.m',EvtType);
        error(msgStr);end
