% Test bed for genC37Signal and AnnexDPmu

F0 = 50;
Fs = 50;
FSamp = 800;
SettlingTime = 14/Fs;
bPosSeq = true(1);
WindowType = 'Hamming';
FilterParams = [7.75,142];

T0 = 0;
Duration = 10.0;
size = FSamp*Duration;

signalParams = zeros(13,3);

signalParams(1,:) =  [70,70,70];          % phase amplitude (given by the user in RMS
signalParams(2,:) = [50,50,50];        % frequency (must be the same for all 6 channels or an error will be thrown
signalParams(3,:) = [0,-120,120];    % phase

% tStart = -SettlingTime;
% tEnd = Duration + SettlingTime;
% t = (tStart:1/FSamp:tEnd);
% EndTime = Duration;
% 
% [Signal] = genC37Signal( ...
%     t, ...
%     FSamp, ...
%     signalParams, ...
%     EndTime ...
%     );


[Signal] = PmuTestSignals( ...
    T0, ...
    SettlingTime/50, ...
    size, ...
    FSamp, ...
    signalParams ...
    );


Signal = Signal.';
%plot (Signal(:,1));

[Timestamp,...
          Synx,...
          Freq,...
          ROCOF] = AnnexDPmu( ...
                        Signal, ...
                        bPosSeq, ...
                        FilterParams, ...
                        WindowType, ...
                        T0, ...
                        F0, ...
                        Fs, ...
                        FSamp, ...
                        SettlingTime ...
                      );  
